archived contact cannot send msg - in progress
nyaruka/temba-components pull request #189
Opened 2022-08-11 10:34 UTC by susanm74

ContactChat.ts
- added check for whether currentContact.status === 'archived'
- TODO - figure out why the runtime archivedContact.status value is 'archived' and not 'V'
- TODO - replace 'archived' with Contact.STATUS_ARCHIVED in check for whether the contact is archived

temba-contact-chat.test.ts
- added test to check that the chatbox div is visibility:hidden
- TODO? - replace 'visibility:hidden' with 'display:none' once the test is closer to working as expected

2022-08-11 17:14 UTC, ericnewcomer commented
Heads up, github has a concept of Draft PRs, so if it's a work in progress you can use that :)

2022-08-11 22:00 UTC, ericnewcomer requested changes
I updated the approach for the test which hopefully makes things a bit more clear.

2022-08-11 22:00 UTC, ericnewcomer commented on src/contacts/ContactChat.ts
> +                            : ''}"
`visibility:hidden` keeps an elements place in the page. I think `display:none` is more likely what we want.

2022-08-11 22:00 UTC, ericnewcomer commented on test-assets/contacts/contact-barak-archived
> +{
You can request static files by just fetching directly `/test-assets/contacts/contact-barak-archived`. This is a pattern you'll see in some places for components that have easily manipulated endpoints. Generally should not have any big json blobs in our tests.

For example, `temba-contact-badges` just appends `uuid` to the `endpoint` attribute. So in its test, it can just change the endpoint it's using and set the uuid to a file in our static files. See here: https://github.com/nyaruka/temba-components/blob/main/test/temba-contact-badges.test.ts#L13

2022-08-11 22:00 UTC, ericnewcomer commented on test/temba-contact-chat.test.ts
> +      contact: 'contact-dave-active',
I added a couple new contacts faux responses, using the clearly invalid uuids of `contact-dave-active` and `contact-barak-archived`. We can add other examples there as needed. There's no uuid validation at this level, so we can really make them whatever we want and I prefer descriptive filenames for these to real uuids.

2022-08-11 22:00 UTC, ericnewcomer commented on test/temba-contact-chat.test.ts
> +  )) as ContactChat;
`getComponent` is nicer than just doing the html bit your self because it'll wrap your element in a parent element with constraints like height, width, etc. In general, we want all of our tests wrapped in a parent element, so we should be updating everybody to use this helper.

2022-08-11 22:00 UTC, ericnewcomer commented on test/temba-contact-chat.test.ts
> +  //   chat.currentContact = archivedContact;
anti-pattern. Avoid setting things explicitly like this. Interact with your component as a user to get it in the state you want. In this case, we want the component to go fetch the contact using the store (with mocked server responses) instead of setting it here.

2022-08-11 22:00 UTC, ericnewcomer commented on test/utils.test.ts
> +  height = 0,
I updated things here to be able to constrain the height for the wrapping the test parent element.

2022-08-11 22:00 UTC, ericnewcomer commented on test-assets/contacts/contact-barak-archived
> +      "status": "archived",
The API always returns descriptive names. Since we are dog fooding things here and fetching these via the API, you'll get translated things like 'archived' instead of 'V'.

2022-08-12 02:18 UTC, susanm74 commented
> Heads up, github has a concept of Draft PRs, so if it's a work in progress you can use that :)

ah, forgot about that, will def use that next time

2022-08-12 02:21 UTC, susanm74 commented on src/contacts/ContactChat.ts
> +                            : ''}"
yeah, for the purpose of testing the test, i wanted to use that so that the div would remain present in the document, but i agree, was planing to switch to display:none once i got an initial iteration of the test fully working

2022-08-12 05:32 UTC, susanm74 commented on test-assets/contacts/contact-barak-archived
> +      "status": "archived",
never heard of dogfooding (TIL)! but sounds like it's ok to keep using 'archived' in the comparison when checking the contact's status, so leaving as is for now

2022-08-12 06:09 UTC, susanm74 commented on test-assets/contacts/contact-barak-archived
> +{
ok cool, will def try to take advantage of test-assets going forward, with the badges and history both being a great reference for how i should be working with those!

2022-08-12 06:13 UTC, susanm74 commented on test/utils.test.ts
> +  height = 0,
i get the idea of consistently wrapping components in a parent element, but why do we set the height to 0? won't this collapse both the parent and child element down such that we can't work with them properly? or does this just prevent any additional parent element height?

2022-08-12 07:56 UTC, susanm74 commented
i noticed in `contact-dave-active.json` and `contact-barack-obama.json` that there is a status prop (which can be active, archived, blocked, or stopped), but then there are also separate `blocked` and `stopped` props... i added more tests for all 4 contact status types, but wasn't sure whether to set contact.status = blocked and/or contact.blocked = true? so for now i just set both (ex. `contact-michelle-blocked.json`, but let me know if i need to update those for tim and michelle?

2022-08-12 10:33 UTC, susanm74 commented
BEFORE
![localhost textit com_contacts_read_4d538970-bba4-43a6-9a25-397bafb7a220_](https://user-images.githubusercontent.com/854012/184337149-606d74b0-84dd-4870-9df8-68a519217815.png)
AFTER
![localhost textit com_contacts_read_4e4cdcc6-7b46-4027-8e0d-4e9a1e094b09_](https://user-images.githubusercontent.com/854012/184337168-f0378e6c-3a0f-4369-8b41-ccaa8417e9a8.png)

2022-08-12 10:37 UTC, susanm74 commented
ooh, i'm just noticing in my before/after screenshots that the pink "Archived" and blue "French" tags are missing, so switched this PR back to draft so that i can look into fixing that on mon

2022-08-12 10:51 UTC, susanm74 commented
hmm, but when i switched from my branch back to the main one i actually don't see those pink "Archived" and blue "French" tags anymore - can someone sanity check whether those were removed from an unrelated change or whether they went missing from my change?

2022-08-12 10:56 UTC, susanm74 commented
also the build's failing, looks like it's due to a pixel mismatch from one of the contact history tests - i don't recall making any changes, but @ericnewcomer let me know if that possibly got messed up from my changes and i can def take a look!

2022-08-12 17:11 UTC, ericnewcomer commented on test/utils.test.ts
> +  height = 0,
Look a bit further down, a height of 0 in this case means don't constrain the height at all. Could have used -1 for that I suppose, but I can't think of a scenario where we'd ever want 0.

2022-08-12 17:16 UTC, ericnewcomer commented
I've actually broken things on `main` 😦 . I had discovered that the upgrade to latest yarn broken versioning. So I unwound those changes and apparently caused other trouble. Will fix and merge changes here.

2022-08-12 17:34 UTC, ericnewcomer commented
I lied, looks like I didn't break anything when unwinding the yarn changes. Looks like an intermittent failure. I think it has to do with how bogged down the instance running our tests is. The test in question initiates a scroll and then waits a bit for the scroll to complete.

I had your failed build rerun and it worked. I'm gonna add a bit to that wait as a precaution too. It'd be nice to maybe figure out how to accomplish that using events instead of timers, but not a priority.

2022-08-12 20:33 UTC, ericnewcomer approved these changes

2022-08-12 20:37 UTC, ericnewcomer commented
I tested this branch, so the issue with your screenshot looks unrelated. So gonna merge it.

I think in the future, it might be nice to show a button to change the contact's status if the chat box is missing, ie, an Unblock button near where the box would be (we do this for closed tickets already)... perhaps a better fit outside of this component though.

2022-08-12 20:38 UTC, merged

2022-08-15 03:26 UTC, susanm74 commented
cool, i agree this could be really nice, i've added it as a task to the new interface space