compose component - switch to media api for attachment uploads
nyaruka/temba-components pull request #276
Opened 2023-03-03 07:31 UTC by susanm74

fixes https://github.com/nyaruka/rapidpro/issues/4347

no changes to UI, no change to happy path for successfully uploaded attachments, some changes needed for handling both nginx and django errors

2023-03-03 14:07 UTC, rowanseymour requested changes

2023-03-03 14:07 UTC, rowanseymour commented on src/compose/Compose.ts
> +          fileError = 'Limit for file uploads is 25.0 MB';
I think this is just your local ngnix.. we have our prod boxes configured to accept much bigger uploads, but the media endpoint itself will return a proper validation error (400) if size is over 25M.

2023-03-06 16:33 UTC, susanm74 commented on src/compose/Compose.ts
> +          fileError = 'Limit for file uploads is 25.0 MB';
@rowanseymour ok so if the django limit is 25MB, and the nginx limit is N (ex. 1GB), and the user tries to upload something bigger than N, and we remove this check for a 413, i think the more generic "Server failure" error will be displayed instead of the "Limit for file uploads is 25MB" error... the latter seems like it would be a bit more accurate, but i'm also fine to remove it and just return the more generic err if that's preferred

2023-03-06 17:06 UTC, rowanseymour commented on src/compose/Compose.ts
> +          fileError = 'Limit for file uploads is 25.0 MB';
There are 3 different places that can enforce a limit - there's a [Django setting](https://docs.djangoproject.com/en/4.1/ref/settings/#data-upload-max-number-files) (default is 2.5MB), there's the media endpoint's own logic, and there's nginx. The nginx limit is currently set pretty high so don't worry about it. The media endpoint is currently set to 25MB and it returns a 400 with a nice error message... I'm not currently sure if the Django setting is being used in prod.. what's the biggest file you can upload?

2023-03-06 18:21 UTC, susanm74 commented on src/compose/Compose.ts
> +          fileError = 'Limit for file uploads is 25.0 MB';
@rowanseymour ok i just tried a file > 1GB on prod, but i still get the "Limit for file uploads is 25MB" error, so the nginx limit must be even higher than that...

but if the upload is bigger than all 3 limits (django, media endpoint, & nginx) i believe a 413 is returned... if we can confirm what the nginx setting is on prod i can def try a bigger file first thing tomorrow morning and re-confirm...

but basically i was just aiming to handle that specific case (aka file size exceeds nginx limit) uniformly if it's due to file size, so that we're displaying the "file size" err msg instead of the generic one...

but again, if you think it's overkill, and the nginx limit is so large that it's rare that a user will ever exceed it, i'm fine to just display the generic "server failure" err msg instead... 

but yeah, when i'm testing locally, i'll sometimes use a lower value for the nginx setting just so i can more easily see what will happen when file upload sizes fall in between the settings or exceeds that one

2023-03-06 18:31 UTC, rowanseymour commented on src/compose/Compose.ts
> +          fileError = 'Limit for file uploads is 25.0 MB';
I checked the prod limit and no-one is going to hit it unless they're really trying to, so don't worry about it here. I don't want to hardcode something about 25MB in the components library when that can change at anytime.

2023-03-08 21:28 UTC, merged